export default API_ENDPOINTS = {
  USER_LOGIN: "users/login",
  USER_SIGNUP: "users/signup",
  FOOD_ADD: "food/add",
  FOOD_DELETE: "food/delete/",
  FOOD_UPDATE: "food/update",
  FOOD_GET: "food/getall",
  FOOD_GET_FILTERED: "food/getfoodbyfilter",
  FOOD_GET_BY_SHARED_BY: "food/getfoodbysharedby",
  FOOD_GET_FOR_CHARITABLE_ORGANIZATION: "food/getfoodforcharitableorganization",
  FOOD_GET_BY_TYPE: "food/getfoodbytype/",
  OTP_SEND: "users/forgetpassword",
  OTP_VERIFY: "users/verifyotp",
  RESET_PASSWORD: "users/resetpassword",
  //OTP
  OTP_SEND_FOR_EMAIL_VERIFICATION: "users/sendotpforemail",
  OTP_VERIFY_EMAIL: "users/verifyotpforemail",
  FOOD_GET_BY_NAME: "food/",
  ADD_LOCATION: "users/location",
  USER_UPDATE: "users/updateprofile",
};
